### ISSUE TITLE
get_scrip_info missing

### ISSUE THREAD

**Issue by vinitshetty** [jerokpradeep/pya3#12]
get_scrip_info used to return scrip information with circuit limit values of that instrument. 

Please support this and keep input/output in the same format

**Comment by Vignesh-Devoloper** [comment]
we have added the get_scrip_info request in version 1.0.12. Please check

**Comment by vinitshetty** [comment]
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/30681948/182417471-f30fd743-5d6c-4505-8a20-89b511ddd10c.png">

**Comment by Vignesh-Devoloper** [comment]
Hi Vinit, Have you downloaded the contract master before these request

**Comment by vinitshetty** [comment]
Yes I did download.

**Comment by Vignesh-Devoloper** [comment]
Check once whether you are inserting the one instrument info to fetch the get_scrip_info response.

**Comment by vinitshetty** [comment]
get_scrip_info is returning list
