### ISSUE TITLE
Not able to Retrieve OrderHistory

### ISSUE THREAD

**Issue by vinitshetty** [jerokpradeep/pya3#13]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/30681948/180438476-381bb5d7-a332-471e-a457-0af17497e6d7.png">

Not able to Retrieve OrderHistory

_Originally posted by @vinitshetty in https://github.com/jerokpradeep/pya3/issues/3#issuecomment-1192518554_

**Comment by Vignesh-Devoloper** [comment]
Hi @vinitshetty 
We have fixed this used in the current update pya3 version 1.0.12. Please check it once after update the library.
