### ISSUE TITLE
How to generate the Session Key

### ISSUE THREAD

**Issue by starkgg123** [jerokpradeep/pya3#14]
Is it possible to generate the Key directly via python without copying it from ant web?
If yes, how?
Also, how to I authorize an app in my other accounts?

**Comment by Vignesh-Devoloper** [comment]
We can generate the **Session Key** through python. But **API key** will not be able to generate through python. The API key once you store it privately from the web to local, will not change until the user regenerates the API.
Follow the code below to generate the session key from python and Copy the API key from the web:
```
from pya3 import *
alice = Aliceblue(user_id='username',api_key='API_KEY')
print(alice.get_session_id())
```

**Comment by starkgg123** [comment]
OK perfect. Thankyou for the quick response.
Lets say I want to make an app and give it to multiple users?
How do I generate an authorization link to authorize my app in another account?

**Comment by Vignesh-Devoloper** [comment]
Hi @starkgg123 
Please refer to this documentation. I hope it will help you [https://v2api.aliceblueonline.com/vendors](url)
