### ISSUE TITLE
Unable to subscribe for Index data

### ISSUE THREAD

**Issue by starkgg123** [jerokpradeep/pya3#17]
all_nifty_scrips = alice.search_instruments('NSE', 'NIFTY')

This does give me a list of all indices with BNF stated as : {'exch': 'NSE', 'exchange_segment': 'INDEX', 'symbol': 'NIFTY BANK', 'token': '26009', 'formattedInsName': 'BANK NIFTY INDEX'}

But I am not able to get the Instrument object for BNF by any of these commands:

>>> alice.get_contract_master("NSE")
NOTE: Today's contract master file will be updated after 08:00 AM. Before 08:00 AM previous day contract file be downloaded.
{'stat': 'ok', 'msg': 'Today contract File Downloaded'}
>>> print(alice.get_instrument_by_symbol('NSE','BANK NIFTY INDEX'))
{'stat': 'Not_ok', 'emsg': 'The symbol is not available in this exchange'}
>>> print(alice.get_instrument_by_symbol('NSE','NIFTY BANK'))
{'stat': 'Not_ok', 'emsg': 'The symbol is not available in this exchange'}
>>> print(alice.get_instrument_by_token('NSE','26009'))
{'stat': 'Not_ok', 'emsg': 'The symbol is not available in this exchange'}
>>> print(alice.get_instrument_by_token('NSE',26009))
{'stat': 'Not_ok', 'emsg': 'The symbol is not available in this exchange'}

Also, I tried to subscribe to BNF data using the code below but it did not work. 

alice = Aliceblue(user_id='abc',api_key='xyz')
print(alice.get_session_id())
print(alice.get_profile())
trd_tkn  = []
trd_tkn.append(Instrument(exchange='NSE', token='26009', symbol='Nifty Bank', name='Nifty Bank', expiry=None, lot_size=None))
alice_sub = Alice_Wrapper()
xyz = alice_sub.subscription(trd_tkn[0])
alice.start_websocket(xyz)

Please provide with a sample code to subscribe to multiple instruments(both indices and stocks).

**Comment by Vignesh-Devoloper** [comment]
Hi @starkgg123 . We updated the subscription for indices in pya3 version 1.0.16. Please update the library and check the following sample code.

`
from pya3 import *

alice = Aliceblue(user_id='user_id',api_key='api_key')
print(alice.get_session_id())
alice.get_contract_master("INDICES")
subscriptions=Alice_Wrapper.subscription([alice.get_instrument_by_symbol('INDICES','NIFTY BANK'),alice.get_instrument_by_token('INDICES',26000)])
alice.start_websocket(subscriptions)
`

**Comment by starkgg123** [comment]
@Vignesh-Devoloper  Thankyou for the quick solution. Can you also fix the websocket continuous printing part?
Thankyou

**Comment by rajamurugan44** [comment]
"signal only works in main thread of the main interpreter" for websocket .. Pls look into it

**Comment by Vignesh-Devoloper** [comment]
Hi @rajamurugan44 . It is fixed in version 1.0.19. Update the library and check once
