### ISSUE TITLE
modify_order fails when given with order_id

### ISSUE THREAD

**Issue by pnandan13a** [jerokpradeep/pya3#18]
unable to place modify_order with order_id. attached error Can you please provide an example as we have in place_order.

![image](https://user-images.githubusercontent.com/43172279/182218655-29f7c853-df27-4cfd-81a5-2f0c4e06ceb6.png)

**Comment by pnandan13a** [comment]
Please let me know if any queries.

**Comment by pnandan13a** [comment]
![image](https://user-images.githubusercontent.com/43172279/182619477-0e521c37-7036-4b19-906c-164c581bda43.png)
 place_order is working but modify_order fails. Was trying with AMO orders. Attached error
Can you please help and provide example of modify_order with usage

**Comment by Vignesh-Devoloper** [comment]
We have fixed the modify order bug in pya3 version 1.0.14. Also, give sample code in the documentation please refer to it.
