### ISSUE TITLE
unable to squareoff open position FNO

### ISSUE THREAD

**Issue by gpaneers** [jerokpradeep/pya3#19]
When we try to cancel order in NFO using below code:
alice.cancel_order('NFO', sell_order_id, sell_strike)

output:
{'stat': 'Ok', 'Result': ' NEST Order Number :220802000017630'}
Exited sell order
{"stat":"Ok","Result":" NEST Order Number :220802000017627"}
Exited buy order

We are getting successful output but position is not getting squared off. Please fix this

**Comment by alandprem** [comment]
It will just cancel your order. It won't exit the open positions.

**Comment by gpaneers** [comment]
So, to square off ,  we need to place opposite orders or we will get an update for square off soon?

**Comment by alandprem** [comment]
> So, to square off , we need to place opposite orders or we will get an update for square off soon?

Yes
