### ISSUE TITLE
Getting same token for different instruments

### ISSUE THREAD

**Issue by Leelamrutha** [jerokpradeep/pya3#22]
![image](https://user-images.githubusercontent.com/110526328/183068450-5f9ba408-f480-4832-8f84-f7546a904560.png)

there is no tickdata information in subscription for example 1minute or 3minute or5minute

**Comment by Vignesh-Devoloper** [comment]
Hi @Leelamrutha , In Version 1.0.20 the historical data is added. please update the library and verify the sample code in the documentation.
