### ISSUE TITLE
get_instrument_by_symbol: Unable to return valid symbol which is inside CSV file

### ISSUE THREAD

**Issue by vinitshetty** [jerokpradeep/pya3#23]
ins=alice.get_instrument_for_fno(exch="NFO",symbol='BANKNIFTY', expiry_date="25-08-2022", is_fut=False,strike=30900, is_CE=True)[0]
print(ins)

ins=alice.get_instrument_by_symbol('NFO','BANKNIFTY22AUG30900CE')
print(ins)

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/30681948/183258598-86528053-85b3-409b-90cb-0ba0749436e6.png">

**Comment by Vignesh-Devoloper** [comment]
In version 1.0.20 is added trading symbol also as a search parameter in 'get_instrument_by_symbol'. Please update the library and try once.
