### ISSUE TITLE
Not able to login.. Getting UnAuthorized

### ISSUE THREAD

**Issue by rajamurugan44** [jerokpradeep/pya3#24]
{'stat': 'Not_ok', 'emsg': '401 - Unauthorized', 'encKey': None}

I am providing my userId and API KEY but getting unAuthorized..

**Comment by Vignesh-Devoloper** [comment]
Hi @rajamurugan44 . Where you have facing the issue exactly while creating session or some other API requests.

**Comment by rajamurugan44** [comment]
Login is working only if I login to application manually.. pls make it automated so that my code will login though I am not logged in to web application

**Comment by alandprem** [comment]
I think you need to log in once to the website and then even if you log out the API key will be running fine.
