### ISSUE TITLE
The symbol is not available in this exchange for Nifty

### ISSUE THREAD

**Issue by rajamurugan44** [jerokpradeep/pya3#25]
alice.get_instrument_by_symbol('NSE', 'NIFTY 50')

{'stat': 'Not_ok', 'emsg': 'The symbol is not available in this exchange'}

Not able to find Nifty 50 index

**Comment by starkgg123** [comment]
You can use this:

Instrument(exchange='NSE', token='26000', symbol='Nifty 50', name='Nifty 50', expiry=None, lot_size=None)

**Comment by rajamurugan44** [comment]
Nifty 50 index is not available in NSE.csv file itself..

**Comment by Vignesh-Devoloper** [comment]
Hi @rajamurugan44 @starkgg123 , We have updated the indices in pya3 library version 1.0.16 to get indices data. Also, I will share the sample to subscribe to the indices.

`
from pya3 import *

alice = Aliceblue(user_id='user_id',api_key='api_key')
print(alice.get_session_id())
alice.get_contract_master("INDICES")
subscriptions=Alice_Wrapper.subscription([alice.get_instrument_by_symbol('INDICES','NIFTY BANK'),alice.get_instrument_by_token('INDICES',26000)])
alice.start_websocket(subscriptions)
`

**Comment by rajamurugan44** [comment]
" error execution signal only works in main thread of the main interpreter"

exception while starting websocket

**Comment by Vignesh-Devoloper** [comment]
Hi @rajamurugan44 . It background run is added in version 1.0.19. Update the library and check once
