### ISSUE TITLE
Error while getting session id

### ISSUE THREAD

**Issue by racha2068** [jerokpradeep/pya3#26]
I am getting error while creating session id in the beginning of the python code. Can you please help to fix this issue?

Error:
"C:\Users\Windows 10\PycharmProjects\AliceBlue\venv\Scripts\python.exe" "C:/Users/Windows 10/PycharmProjects/AliceBlue/main.py" 
{'stat': 'Not_Ok', 'emsg': 'Invalid Input'}

Process finished with exit code 0

**Comment by racha2068** [comment]
This is my code
from pya3 import *
alice = Aliceblue(user_id="KAH1619",  api_key="sl4z6oB6DCDpPjzMkxnYPVAK2IQkNCKOUUHpmvUo2IGJYT3ugLacy44VHirl4aClueHNNDb3Oh0OaGnqTPdDpInKug5kazaElqdVbcuug2VJs71n6eC3snqrI3H8yxzY")
print(alice.get_session_id())

**Comment by alandprem** [comment]
It's working fine for me.

alice = Aliceblue(user_id=account['username'], api_key= account['api_key'])
result = alice.get_session_id()

api_key should be generated from the new website --> https://a3.aliceblueonline.com/apps?tab=API

**Comment by Vignesh-Devoloper** [comment]
Hi @racha2068 . The error message indicates you have given the wrong API key. Please get the API key from https://a3.aliceblueonline.com/apps?tab=API
