### ISSUE TITLE
WebSocket Callback method code example usage for parsing websocket data

### ISSUE THREAD

**Issue by pnandan13a** [jerokpradeep/pya3#28]
Subscriptions should run in BackGround. It keeping displaying websocket data in the terminal\window
Can we also have the subscriptions run in background. 

           After subscribing to websocket, how do we read the data from web socket?

subscriptions=Alice_Wrapper.subscription([alice.get_instrument_by_token("NFO",47558),alice.get_instrument_by_token("NFO",47559)])
alice.start_websocket(subscriptions)

{"t":"tf","e":"NFO","tk":"47559","lp":"299.75","pc":"-25.60","ft":"1660295011"}
{"t":"tf","e":"NFO","tk":"47558","lp":"291.90","pc":"-3.57","ft":"1660295011"}

    Can you please share  WebSocket Callback method code example usage for parsing websocket data.

**Comment by pnandan13a** [comment]
Can we also have the subscriptions run in background. It keeping displaying everything in the terminal\window

**Comment by devbbsr123** [comment]
Yes this big issue of us, hope it will resolve next week.

**Comment by devbbsr123** [comment]
We are waiting from last week, but still no solutions updated

**Comment by Vignesh-Devoloper** [comment]
Hi @devbbsr123 and @pnandan13a . Call back function for open, message, close, and error is added in version 1.0.19. Update the library and check once

**Comment by pnandan13a** [comment]
Thanks for the fix. Ticket is good closure
