### ISSUE TITLE
Socket Not working on background thread

### ISSUE THREAD

**Issue by RRR008** [jerokpradeep/pya3#30]
I am getting below error if I put start socket code into a method
<img width="1115" alt="Screenshot 2022-08-17 at 10 48 16 AM" src="https://user-images.githubusercontent.com/108396628/185040491-74d03875-8e0f-41cc-9f24-8bca3425db3a.png">

NOTE: Today's contract master file will be updated after 08:00 AM. Before 08:00 AM previous day contract file be downloaded.
Subscription List:
Exchange: NSE ,Symbol: NIFTY BANK ,Token: 26009
Exchange: NSE ,Symbol: NIFTY 50 ,Token: 26000
-----------------------------------------------------------------------------------
STAGE 1: Invalidate the previous session : Ok
STAGE 2: Create the new session : Ok
Connecting to Socket ...
Error: signal only works in main thread of the main interpreter

**Comment by devbbsr123** [comment]
Update about this matter plz

**Comment by Nagarjun-alt** [comment]
New update is released for this, kindly find the attachment https://v2api.aliceblueonline.com/websocket

**Comment by RRR008** [comment]
Hi @Nagarjun-alt ,

def RunAlgoClick1():
socket_opened = False
	subscribe_flag = False
	def feed_data(message):  # Socket feed data will receive in this callback function
	    global LTP, subscribe_flag
	    feed_message = json.loads(message)
	    if feed_message["t"] == "ck":
	        print("Connection Acknowledgement status :%s (Websocket Connected)" % feed_message["s"])
	        subscribe_flag = True
	        print("subscribe_flag :", subscribe_flag)
	        print("-------------------------------------------------------------------------------")
	        pass
	    elif feed_message["t"] == "tk":
	        print("Token Acknowledgement status :%s " % feed_message)
	        print("-------------------------------------------------------------------------------")
	        pass
	    else:
	        print("Feed :", feed_message)
	        LTP = feed_message[
	            'lp'] if 'lp' in feed_message else LTP  # If LTP in the response it will store in LTP variable

	def subscription_list(subscrip_list):
	    print("Subscription List:")
	    for list in subscrip_list:
	        print("Exchange: %s ,Symbol: %s ,Token: %s"%(list.exchange,list.symbol,list.token))
	    print("-----------------------------------------------------------------------------------")

	def socket_open():  # Socket open callback function
	    print("Connected")
	    global socket_opened
	    socket_opened = True
	    if subscribe_flag:  # This is used to resubscribe the script when reconnect the socket.
	        alice.subscribe(subscribe_list)

	def socket_close():  # On Socket close this callback function will trigger
	    global socket_opened, LTP
	    socket_opened = False
	    LTP = 0
	    print("Closed")

	def socket_error(message):  # Socket Error Message will receive in this callback function
	    global LTP
	    LTP = 0
	    print("Error :", message)
	def start_socket():
		# alice.get_contract_master("INDICES")
		# subscriptions=Alice_Wrapper.subscription([alice.get_instrument_by_symbol('INDICES','NIFTY BANK'),alice.get_instrument_by_token('INDICES',26000)])
		alice.start_websocket(socket_open_callback=socket_open, socket_close_callback=socket_close,
                      socket_error_callback=socket_error, subscription_callback=feed_data, run_in_background=True)
		while not socket_opened:
			pass
		global subscribe_list, unsubscribe_list

		subscribe_list = [alice.get_instrument_by_token('INDICES', 26000)]
		alice.subscribe(subscribe_list)
		print(datetime.now())
		sleep(10)
		print(datetime.now())
I have created a function called RunAlgoClick1 which I am calling on button click it seems like socket is getting connected but callback function for feed is not printing any data, ideally it should print tick data after the below response.

Here is the response I am getting:
STAGE 1: Invalidate the previous session : Ok
STAGE 2: Create the new session : Ok
Connecting to Socket ...
Connected
Connection Acknowledgement status :OK (Websocket Connected)
subscribe_flag : True
-------------------------------------------------------------------------------

**Comment by Vignesh-Devoloper** [comment]
Hi @RRR008 . We have updated the sample code again please initialize the variable and try it once
<img width="325" alt="image" src="https://user-images.githubusercontent.com/104829128/185847192-6ca11f0d-4b3b-498a-8667-651e43fccb15.png">

**Comment by Vignesh-Devoloper** [comment]
Hi @devbbsr123. The Background run thread is added in pya3 version 1.0.19. Update the library check once.

**Comment by RRR008** [comment]
Hi @Vignesh-Devoloper ,
I have tried with the variable declaration you have mentioned still getting same output.
You can try replicating my code and check.
Thank You.

**Comment by Vignesh-Devoloper** [comment]
Sure @RRR008  ping me in telegram and let me check what is the issue.

**Comment by RRR008** [comment]
Hi @Vignesh-Devoloper ,
Please let me know your Telegram id

**Comment by Vignesh-Devoloper** [comment]
Hi @RRR008 . After updating the pya3 library version 1.0.20 the issue has been solved.
