### ISSUE TITLE
OHLC not available in live feed

### ISSUE THREAD

**Issue by rajamurugan44** [jerokpradeep/pya3#32]
Subscribed to Nifty and BankNifty and its not giving Open, High, Low and Close price in response.

{'t': 'tf', 'e': 'NSE', 'tk': '26000', 'lp': '17504.85', 'pc': '-0.41', 'ft': '1661314258'}
{'t': 'tf', 'e': 'NSE', 'tk': '26009', 'lp': '38618.30', 'pc': '-0.21', 'ft': '1661314258'}
{'t': 'tf', 'e': 'NSE', 'tk': '26000', 'lp': '17505.10', 'pc': '-0.41', 'ft': '1661314259'}
{'t': 'tf', 'e': 'NSE', 'tk': '26009', 'lp': '38619.95', 'pc': '-0.20', 'ft': '1661314259'}
{'t': 'tf', 'e': 'NSE', 'tk': '26009', 'lp': '38621.60', 'pc': '-0.20', 'ft': '1661314260'}
{'t': 'tf', 'e': 'NSE', 'tk': '26000', 'lp': '17507.20', 'pc': '-0.40', 'ft': '1661314260'}

Pls add OHLC as well in websocket subscribe..

**Comment by Vignesh-Devoloper** [comment]
Hi @rajamurugan44 , you will get OHLC data from token acknowledgment which the feed will come at initial. To identify the feed and feed acknowledgment please check the parameter 't'.
Response explanation:
'tf'-tick Feed
'tk'-tick acknowledgment
If the change occurs in High and Low it will update in the tick feed.
