### ISSUE TITLE
alice.get_order_history always throws error 

### ISSUE THREAD

**Issue by RRR008** [jerokpradeep/pya3#33]
Hi @Vignesh-Devoloper ,
I am trying to get the order history from the below code but I am always getting error messgae:
Code:
instrument_s = alice.get_instrument_by_symbol('INDICES','NIFTY BANK')
transaction_ordernumber = trasaction_order[0]['NOrdNo']
order_history = alice.get_order_history(instrument_s,transaction_ordernumber)

Error:
Error : Aliceblue.get_order_history() takes 2 positional arguments but 3 were given

If the code with token I getting the below error:

Code:
instrument_s = alice.get_instrument_by_symbol('INDICES',26009)
transaction_ordernumber = trasaction_order[0]['NOrdNo']
order_history = alice.get_order_history(instrument_s,transaction_ordernumber)

Error:
Error : 'int' object has no attribute 'upper'

**Comment by Vignesh-Devoloper** [comment]
Hi @RRR008 . In version 1.0.20 get_instrument_by_token is not required to fetch single order history. The Document is updated please verify the documentation once for reference.
