### ISSUE TITLE
Place PUT buy but still Taking CALL buy and wrong symbol -  name='BANKNIFTY22AUG39300PE', expiry='2022-08-25'

### ISSUE THREAD

**Issue by RRR008** [jerokpradeep/pya3#35]
Hi @jerokpradeep ,

I have placed put buy but it still taking Call buy please check below code and response also getting wrong symbol check the date and symbol.
Code:
put_trasaction_order = alice.place_order(transaction_type = TransactionType.Buy,
											 instrument = alice.get_instrument_by_symbol('NFO', put_order_symbol),
											 quantity = int(final_put_lot_value),
											 order_type = OrderType.Market,
											 product_type = ProductType.Intraday,
											 price = 0.0,
											 trigger_price = None,
											 stop_loss = None,
											 square_off = None,
											 trailing_sl = None,
											 is_amo = False)
Response:
place sell order
put round_strike_price 39300
bno data put Instrument(exchange='NFO', token=35095, symbol='BANKNIFTY', name='BANKNIFTY22AUG39300PE', expiry='2022-08-25', lot_size=25)
order_history {'Prc': '00.00', 'RequestID': '1', 'Cancelqty': 0, 'discQtyPerc': 'NA', 'customText': 'NA', 'Mktpro': 'NA', 'defmktproval': '3', 'optionType': 'CE', 'usecs': '969379', 'mpro': '1', 'Qty': 25, 'ordergenerationtype': '--', 'Unfilledsize': 0, 'orderAuthStatus': '', 'Usercomments': 'NA', 'ticksize': '5', 'Prctype': 'MKT', 'Status': 'rejected', 'Minqty': 0, 'orderCriteria': 'NA', 'Exseg': 'nse_fo', 'Sym': 'BANKNIFTY', 'multiplier': '1', 'ExchOrdID': 'NA', 'ExchConfrmtime': '--', 'Pcode': 'MIS', 'SyomOrderId': '', 'Dscqty': 0, 'Exchange': 'NFO', 'Ordvaldate': 'NA', 'accountId': '672398', 'exchangeuserinfo': '111111111111100', 'Avgprc': '00.00', 'Trgprc': '00.00', 'Trantype': 'B', 'bqty': '25', 'Trsym': 'BANKNIFTY22AUG30900CE', 'Fillshares': 0, 'AlgoCategory': 'NA', 'sipindicator': 'N', 'strikePrice': '30900.00', 'reporttype': 'failure', 'AlgoID': 'NA', 'noMktPro': '0', 'BrokerClient': '--', 'OrderUserMessage': '', 'decprec': '2', 'ExpDate': '25 Aug, 2022', 'COPercentage': 0.0, 'marketprotectionpercentage': '--', 'Nstordno': '220825000075111', 'ExpSsbDate': '1345905000', 'OrderedTime': '25/08/2022 10:13:11', 'RejReason': 'RMS:Rule: Check circuit limit including square off order exceeds  for entity account-672398 across exchange across segment across product ', 'modifiedBy': '--', 'Scripname': '', 'stat': 'Ok', 'orderentrytime': 'Aug 25 2022 10:13:11', 'PriceDenomenator': '1', 'panNo': 'BNWPS6794P', 'RefLmtPrice': 0.0, 'PriceNumerator': '1', 'token': '35018', 'ordersource': 'NEST_REST_WEB', 'Validity': 'DAY', 'GeneralDenomenator': '1', 'series': 'XX', 'InstName': 'OPTIDX', 'GeneralNumerator': '1', 'user': '672398', 'remarks': '--', 'iSinceBOE': 1661402591}
order rejected hence could not proceed ahead
Put order initiated

**Comment by Vignesh-Devoloper** [comment]
Hi @RRR008 , This is for testing purposes. Please request the place order with the order tag as "Testing_API" and share the request and response. so that we can identify whether the order is placed from our end.

**Comment by RRR008** [comment]
Hi @Vignesh-Devoloper ,
I am Still getting same response instead of call, put is taken. please check the reponse:

put round_strike_price 39200
bno data put Instrument(exchange='NFO', token=35091, symbol='BANKNIFTY', name='BANKNIFTY22AUG39200PE', expiry='2022-08-25', lot_size=25)
order_history {'Prc': '00.00', 'RequestID': '1', 'Cancelqty': 0, 'discQtyPerc': 'NA', 'customText': 'NA', 'Mktpro': 'NA', 'defmktproval': '3', 'optionType': 'CE', 'usecs': '084504', 'mpro': '1', 'Qty': 25, 'ordergenerationtype': '--', 'Unfilledsize': 0, 'orderAuthStatus': '', 'Usercomments': 'NA', 'ticksize': '5', 'Prctype': 'MKT', 'Status': 'rejected', 'Minqty': 0, 'orderCriteria': 'NA', 'Exseg': 'nse_fo', 'Sym': 'BANKNIFTY', 'multiplier': '1', 'ExchOrdID': 'NA', 'ExchConfrmtime': '--', 'Pcode': 'MIS', 'SyomOrderId': '', 'Dscqty': 0, 'Exchange': 'NFO', 'Ordvaldate': 'NA', 'accountId': '672398', 'exchangeuserinfo': '111111111111100', 'Avgprc': '00.00', 'Trgprc': '00.00', 'Trantype': 'B', 'bqty': '25', 'Trsym': 'BANKNIFTY22AUG30900CE', 'Fillshares': 0, 'AlgoCategory': 'NA', 'sipindicator': 'N', 'strikePrice': '30900.00', 'reporttype': 'failure', 'AlgoID': 'NA', 'noMktPro': '0', 'BrokerClient': '--', 'OrderUserMessage': '', 'decprec': '2', 'ExpDate': '25 Aug, 2022', 'COPercentage': 0.0, 'marketprotectionpercentage': '--', 'Nstordno': '220825000125361', 'ExpSsbDate': '1345905000', 'OrderedTime': '25/08/2022 11:29:37', 'RejReason': 'RMS:Rule: Check circuit limit including square off order exceeds  for entity account-672398 across exchange across segment across product ', 'modifiedBy': '--', 'Scripname': '', 'stat': 'Ok', 'orderentrytime': 'Aug 25 2022 11:29:37', 'PriceDenomenator': '1', 'panNo': 'BNWPS6794P', 'RefLmtPrice': 0.0, 'PriceNumerator': '1', 'token': '35018', 'ordersource': 'NEST_REST_WEB', 'Validity': 'DAY', 'GeneralDenomenator': '1', 'series': 'XX', 'InstName': 'OPTIDX', 'GeneralNumerator': '1', 'user': '672398', 'remarks': 'Testing_API', 'iSinceBOE': 1661407177}
order rejected hence could not proceed ahead
Put order initiated

**Comment by Vignesh-Devoloper** [comment]
Also, share the place order request. @RRR008

**Comment by RRR008** [comment]
Hi @Vignesh-Devoloper , here is the request I have placed: 
bn_put = alice.get_instrument_for_fno(exch="NFO",symbol = 'BANKNIFTY', expiry_date=cal.get(), is_fut=False, strike=put_round_strike_price, is_CE = False)
	
		put_order_symbol = bn_put.symbol
		
		final_put_lot_value = 0
		if put_order_placed_counter == 0:
			final_put_lot_value = 25
		elif put_order_placed_counter == 1:
			final_put_lot_value = 50
		elif put_order_placed_counter == 2:
			final_put_lot_value = 100
		elif put_order_placed_counter == 3:
			final_put_lot_value = 200
		elif put_order_placed_counter == 4:
			final_put_lot_value = 400
		elif put_order_placed_counter == 5:
			final_put_lot_value = 800

		
		put_trasaction_order = alice.place_order(transaction_type = TransactionType.Buy,
											 instrument = alice.get_instrument_by_symbol('NFO', put_order_symbol),
											 quantity = int(final_put_lot_value),
											 order_type = OrderType.Market,
											 product_type = ProductType.Intraday,
											 price = 0.0,
											 trigger_price = None,
											 stop_loss = None,
											 square_off = None,
											 trailing_sl = None,
											 is_amo = False,
											 order_tag='Testing_API')

**Comment by Vignesh-Devoloper** [comment]
To Place a call order you have to change the code like this
`
call_order_symbol='BANKNIFTY22AUG39200CE'

call_trasaction_order = alice.place_order(transaction_type = TransactionType.Buy,
										 instrument = alice.get_instrument_by_symbol('NFO', call_order_symbol),
										 quantity = int(final_put_lot_value),
										 order_type = OrderType.Market,
										 product_type = ProductType.Intraday,
										 price = 0.0,
										 trigger_price = None,
										 stop_loss = None,
										 square_off = None,
										 trailing_sl = None,
										 is_amo = False,
										 order_tag='Testing_API')
`

**Comment by RRR008** [comment]
HI @Vignesh-Devoloper , call order is working fine what I am saying is when I am placing a PUT order it's only Taking CALL.
