### ISSUE TITLE
Need Open Interest data in websocket

### ISSUE THREAD

**Issue by sreeramtkd** [jerokpradeep/pya3#36]
Please refer to this section

![image](https://user-images.githubusercontent.com/25638554/186584907-ea4c2d40-7aea-4ceb-a6e6-652fde546dd0.png)

**Comment by Vignesh-Devoloper** [comment]
Hi @sreeramtkd , At the token acknowledgment, you will get all the data of the script to which you subscribe. If there is not any change in the high, low, oi, and the last price in the parameter it will not update in the feed. If any change occurs in the parameter it will be updated in the feed.

**Comment by devbbsr123** [comment]
Actually I think we facing a lot of problem with new version. Plz help us for solutions.

**Comment by Vignesh-Devoloper** [comment]
Hi @devbbsr123 , we have updated the pya3 version 1.0.21. If you have any issues in pya3 till now. Please raise an issue in github.
