### ISSUE TITLE
get_session_id() not returning json on failure

### ISSUE THREAD

**Issue by mimaya** [jerokpradeep/pya3#42]
get_session_id() return json object on success
{'stat': 'Ok', 'sessionID': ''} 
 but give error string on failure 
'User does not login. Please login'

Can you make failure also to return json

**Comment by Vignesh-Devoloper** [comment]
Hi @mimaya , Changed the get_session_id() error response format from string to JSON in pya3 version 1.0.22. Please update and check once.

**Comment by mimaya** [comment]
Thanks, now its returning json on errors
