### ISSUE TITLE
Instrument Object Type Inconsistency

### ISSUE THREAD

**Issue by vinitshetty** [jerokpradeep/pya3#5]
Expected Instrument Type:

Instrument(exchange='BSE', token=1, symbol='SENSEX', name='SENSEX', expiry=None, lot_size=None)

<img width="882" alt="image" src="https://user-images.githubusercontent.com/30681948/179491519-1bd796c9-bf7d-4815-a823-3edddd86d555.png">

Returned Type:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/30681948/179491597-e966ed10-d1fe-4c7c-8d82-571266227ca5.png">

**Comment by Vignesh-Devoloper** [comment]
An instrumented object is no need for this pya3 library. Also removed from the documentation.

**Comment by vinitshetty** [comment]
@Vignesh-Devoloper @jerokpradeep 

Pradeep agreeed that this library should be backward compatibe with the older version here https://github.com/krishnavelu/alice_blue

Otherwise we have to re-write whole app.

Can you please keep skeleton same - meaning keep Instrument object and map your columns. If there are more columns in new API add them, but don't remove/break existing structure.

**Comment by vinitshetty** [comment]
same applies for @issue #9

**Comment by Vignesh-Devoloper** [comment]
It will be updated in an upcoming version.

**Comment by Vignesh-Devoloper** [comment]
Hi @vinitshetty 
We have updated the pya3 version 1.0.12, Instrument Object in FNO, symbol, and token search are added in the 1.0.12 version.
