### ISSUE TITLE
Webscoket is missing

### ISSUE THREAD

**Issue by vinitshetty** [jerokpradeep/pya3#6]
No way to initiate or subscribe to symbols

**Comment by Vignesh-Devoloper** [comment]
In current pya3 version we don't have the WebSocket. In future we will update in this library.

**Comment by vinitshetty** [comment]
Hi Vignesh,

As you know pretty much every broker supports websocket natively via
python.

Can you please use old template and make it work with new APIs.

Honestly we can't use separate implementation for websocket which is a
critical component for every algo.

**Comment by Vignesh-Devoloper** [comment]
Hi @vinitshetty 
We have added the Websocket in pya3 version 1.0.12. For sample code please refer to the documentation.
