### ISSUE TITLE
historical data api not working

### ISSUE THREAD

**Issue by bhvarshn** [jerokpradeep/pya3#61]
Hi I am using below code and historical data api is not working

instrument = alice.get_instrument_by_symbol("NFO", "RELIANCE")
from_datetime = datetime.datetime.now() - datetime.timedelta(days=1) # From last & days
to_datetime = datetime.datetime.now() # To now
interval = "D" # ["1", "D"]
indices = False # For Getting index data
print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))

Error
C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/bhvarshn/PycharmProjects/pythonProject/AliceblueV2apisupport/Testcode/historicaldata.py
Traceback (most recent call last):
File "C:/Users/bhvarshn/PycharmProjects/pythonProject/AliceblueV2apisupport/Testcode/historicaldata.py", line 174, in
print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))
File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\pya3\alicebluepy.py", line 831, in get_historical
lst = requests.get(f"https://a3.aliceblueonline.com/rest/AliceBlueAPIService/chart/history?", params=params).json()
File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\requests\models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json_init_.py", line 357, in loads
return _default_decoder.decode(s)
File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

this api was working last week in market hours also. Can you please help to understand what you mean by " Data only available in Non Market hours"
I was testing my algo tool and it was perfectly working in market hours and in non market hours. Not sure what you guys changed after that it stopped working. Please clarify how to fetch historical data .This is urgent. Thanks

File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\pya3\alicebluepy.py", line 831, in get_historical
lst = requests.get(f"[https://a3.aliceblueonline.com/rest/AliceBlueAPIService/chart/history?",params=params).json(](https://a3.aliceblueonline.com/rest/AliceBlueAPIService/chart/history?%22,params=params).json())
Please check why this line is failing in file alicebluepy.py

**Comment by Vignesh-Devoloper** [comment]
Hi @bhvarshn It is an older version of the historical data API. In V2 currently, we have only one min and a day resolution. We are working on the 10-year intra-day data and all resolutions also. Once it is completed we will update you in telegram or in this same medium.

**Comment by bhvarshn** [comment]
Thanks for ur reply. This api is not even working for Day resolution . Please clarify how it was working last week. 
What you guys changed after which it stopped working . This is urgent as my whole algo stopped working due to this api failure.revert all changes you guys have done in GIT for historical data api to make it work. Thanks

**Comment by bhvarshn** [comment]
Thanks for ur reply. This api is not even working for Day resolution .
Please clarify how it was working last week.
What you guys changed after which it stopped working . This is urgent as my
whole algo stopped working due to this api failure.revert all changes you
guys have done in GIT for historical data api to make it work. Thanks

**Comment by Shekharkilche1** [comment]
Hi, 
I am also facing a similar issue from last Friday i.e. 7th October 2022, please find my code and errors as follows:

**Code:**
    instrument=(alice.get_instrument_by_token('INDICES',26000))#alice.get_instrument_by_token('INDICES',26000)
    from_datetime = dt.datetime.now() - dt.timedelta(days=3)    # From last & days
    to_datetime = dt.datetime.now()                                    # To now
    interval = "1"       # ["1", "2", "3", "4", "5", "10", "15", "30", "60", "120", "180", "240", "D", "1W", "1M"]
    indices = True      # For Getting index data
    
    df=alice.get_historical(instrument, from_datetime, to_datetime, interval, indices)
 
**Error:**
 df=alice.get_historical(instrument, from_datetime, to_datetime, interval, indices)

  File ~\.conda\envs\nifty500\lib\site-packages\pya3\alicebluepy.py:831 in get_historical
    lst = requests.get(f"https://a3.aliceblueonline.com/rest/AliceBlueAPIService/chart/history?", params=params).json()

  File ~\.conda\envs\nifty500\lib\site-packages\requests\models.py:975 in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value

**Comment by bhvarshn** [comment]
team please update . what changes you guys have done after which historical data api stopped working.This is urgent

**Comment by bhvarshn** [comment]
team please update . This is urgent

**Comment by bhvarshn** [comment]
team any update on this . please revert changes due to which collateral of code happened.thanks

**Comment by bhvarshn** [comment]
No updates yet.

**Comment by bhvarshn** [comment]
any update

**Comment by Shekharkilche1** [comment]
Please Update

**Comment by Vignesh-Devoloper** [comment]
Hi @bhvarshn @Shekharkilche1 please check whether you adding the authorization or not. Because the current version requires authorization for historical data requests.

```
alice = Aliceblue(user_id='username',api_key='API_KEY')
```
Add the above code and place your user ID and API key in the input

```
print(alice.get_session_id()) # Get Session ID
```
Check the above code whether your user ID and API key are valid or not

**Comment by bhvarshn** [comment]
Common Vignesh . These are basic things and we are taking care of the valid session id. 
You still have not answered what is changed by your team after which code stopped working from 7th Oct. Please read earlier replies of mine. Thanks

**Comment by Vignesh-Devoloper** [comment]
In the new version, nothing is changed @bhvarshn. Only authorization is added in the current version. Try to run the below code with your user id and API key and share the response

```
from pya3 import *
import datetime

alice = Aliceblue(user_id=user_id,api_key=api_key)

session=alice.get_session_id()
print("###############################################  SESSION  #####################################################")
print("Session ID :",session)

instrument = alice.get_instrument_by_symbol("INDICES", "NIFTY BANK")
from_datetime = datetime.datetime.now() - datetime.timedelta(days=7) # From last & days
to_datetime = datetime.datetime.now() # To now
interval = "D" # ["1", "D"]
indices = True # For Getting index data
print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))
```

**Comment by bhvarshn** [comment]
Still the same error. I just changed last 5 letters for security. I cannot share same apikey here due to security reasons

from pya3 import *
import datetime
apikey = 'HGMLOPMFJFsCjQQCd5phLYhWELbm8kEVfJJSglbVn41cdgEUGQDRFvJ2tiaF' \
             '8UBcWQBysyjPEs10B3d8VFm8WneAWWWDux8Ctv02MBTsRYHt9pCPiySi3g2Q1FZzxxxxx'
alice = Aliceblue(user_id='347824', api_key=apikey)

session=alice.get_session_id()
print("###############################################  SESSION  #####################################################")
print("Session ID :",session)

instrument = alice.get_instrument_by_symbol("INDICES", "NIFTY BANK")
from_datetime = datetime.datetime.now() - datetime.timedelta(days=7) # From last & days
to_datetime = datetime.datetime.now() # To now
interval = "D" # ["1", "D"]
indices = True # For Getting index data
print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))



C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/bhvarshn/PycharmProjects/pythonProject/AliceblueV2apisupport/Testcode/historicaldata.py
###############################################  SESSION  #####################################################
Session ID : {'stat': 'Ok', 'sessionID': '0hVZCxdR1bEHMSu73oTNBxIzg7GP1KRmHrXLEEzxIXxS1yIBjVvK8797qLLi7mgok1ySQu0X0t2pEOgNUpjtGshsrnnMjBBlas75QiIPCoV5fcA41J5eOQpNFTDV12xch6epIYhMYdK9zC2Oy5bRzFbR4Tb7SlejiMrt0AE53tBpIi0IOWmtI6yI31lC7sfRePljk46FbifqJbSlz42hiTXXvAdTcXVvHgLiVhDlp8x1eotYkOFAttQ0ancmIHKm'}
Traceback (most recent call last):
  File "C:/Users/bhvarshn/PycharmProjects/pythonProject/AliceblueV2apisupport/Testcode/historicaldata.py", line 17, in <module>
    print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\pya3\alicebluepy.py", line 831, in get_historical
    lst = requests.get(f"https://a3.aliceblueonline.com/rest/AliceBlueAPIService/chart/history?", params=params).json()
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

**Comment by Vignesh-Devoloper** [comment]
@bhvarshn may I know which version you using in pya3?

**Comment by bhvarshn** [comment]
My Version was 1.0.25
I upgraded to 1.0.27 and after that code is working fine. 
Thanks for ur input and help in resolving issue.

Thanks again


              datetime     open      high      low    close  volume
0  2022-10-17 00:00:00  39295.6  39884.35  39146.7  39305.6     0.0

Process finished with exit code 0

**Comment by bhvarshn** [comment]
Cancel order is not working either for "ExchOrdID" or "Nstordno "
print(alice.cancel_order('1200000002127533'))
Below is pending and open order data .

Prc RequestID  Cancelqty discQtyPerc customText Mktpro defmktproval
optionType   usecs mpro  Qty ordergenerationtype  Unfilledsize
orderAuthStatus Usercomments ticksize Prctype           Status  Minqty
orderCriteria   Exseg   Sym multiplier         ExchOrdID
 ExchConfrmtime Pcode      SyomOrderId  Dscqty Exchange Ordvaldate
accountId exchangeuserinfo  Avgprc  Trgprc Trantype bqty    Trsym
 Fillshares AlgoCategory sipindicator strikePrice reporttype AlgoID
noMktPro BrokerClient OrderUserMessage decprec ExpDate  COPercentage
marketprotectionpercentage         Nstordno ExpSsbDate          OrderedTime
RejReason modifiedBy                  Scripname stat        orderentrytime
PriceDenomenator       panNo  RefLmtPrice PriceNumerator token
 ordersource Validity GeneralDenomenator series InstName GeneralNumerator
 user remarks   iSinceBOE

144   134.75         2          0          10         NA     NA
 3         XX  578362    1   82                  --            82
                NA        5      SL  trigger pending       0            NA
 nse_cm  ONGC          1  1200000002127533  24-Nov-2022 13:44:14    BO
 221124000024578      82      NSE         NA    622648  111111111111000
00.00  136.35        S    1  ONGC-EQ           0            0            N
      00.00  sl modify  54407        0           --                1
2      NA           0.0                         --  221124000024580
NA  24/11/2022 13:44:14        --     622648  OIL AND NATURAL GAS CORP.
Ok  Nov 24 2022 09:30:15                1  ACEPL9131B          0.0
     1  2475                       --      DAY                  1     EQ
                      1  622648      --  1669277654

145   134.75         2          0          10         NA     NA
 3         XX  629884    1  100                  --           100
                NA        5      SL  trigger pending       0            NA
 nse_cm  ONGC          1  1200000002127535  24-Nov-2022 13:44:14    BO
 221124000024578     100      NSE         NA    622648  111111111111000
00.00  136.35        S    1  ONGC-EQ           0            0            N
      00.00  sl modify  54407        0           --                2
2      NA           0.0                         --  221124000024582
NA  24/11/2022 13:44:14        --     622648  OIL AND NATURAL GAS CORP.
Ok  Nov 24 2022 09:30:15                1  ACEPL9131B          0.0
     1  2475                       --      DAY                  1     EQ
                      1  622648      --  1669277654

2511  150.15         1          0          10         NA     NA
 3         XX  516295    1   82                  --            82
                NA        5       L             open       0            NA
 nse_cm  ONGC          1  1200000002127532  24-Nov-2022 09:30:15    BO
 221124000024578      82      NSE         NA    622648  111111111111000
00.00   00.00        S    1  ONGC-EQ           0            0            N
      00.00     status  54407        0           --                1
2      NA           0.0                         --  221124000024579
NA  24/11/2022 09:30:15        --         --  OIL AND NATURAL GAS CORP.
Ok  Nov 24 2022 09:30:15                1  ACEPL9131B          0.0
     1  2475                       --      DAY                  1     EQ
                      1  622648      --  1669262415

2512   00.00         1          0          10         NA     NA
 3         XX  512932    1  182                  --             0
                NA        5       L         complete       0            NA
 nse_cm  ONGC          1  1200000002127528  24-Nov-2022 09:30:15    BO
                   0      NSE         NA    622648  111111111111000  138.00
  00.00        B    1  ONGC-EQ         182            0            N
00.00       fill  54407        0           --                        2
 NA           0.0                         --  221124000024578         NA
 24/11/2022 09:30:15        --         --  OIL AND NATURAL GAS CORP.   Ok
 Nov 24 2022 09:30:15                1  ACEPL9131B          0.0
 1  2475  NEST_REST_NEST_REST_API      DAY                  1     EQ
                  1  622648      --  1669262415

2513  150.15         1          0          10         NA     NA
 3         XX  516550    1  100                  --           100
                NA        5       L             open       0            NA
 nse_cm  ONGC          1  1200000002127534  24-Nov-2022 09:30:15    BO
 221124000024578     100      NSE         NA    622648  111111111111000
00.00   00.00        S    1  ONGC-EQ           0            0            N
      00.00     status  54407        0           --                2
2      NA           0.0                         --  221124000024581
NA  24/11/2022 09:30:15        --         --  OIL AND NATURAL GAS CORP.
Ok  Nov 24 2022 09:30:15                1  ACEPL9131B          0.0
     1  2475                       --      DAY                  1     EQ
                      1  622648      --  1669262415 2022-11-24 14:08:45

Order Id: 1200000002127533 Status: trigger pending 2022-11-24 14:08:46

Status is: 2022-11-24 14:08:46

{'stat': 'Not_Ok', 'Emsg': 'No Data'} 2022-11-24 14:08:46

Order Id: 1200000002127535 Status: trigger pending 2022-11-24 14:08:46

Status is: 2022-11-24 14:08:46

{'stat': 'Not_Ok', 'Emsg': 'No Data'} 2022-11-24 14:08:46

Order Id: 1200000002127532 Status: open 2022-11-24 14:08:46

Status is: 2022-11-24 14:08:47

{'stat': 'Not_Ok', 'Emsg': 'No Data'} 2022-11-24 14:08:47

Order Id: 1200000002127534 Status: open 2022-11-24 14:08:47

Status is: 2022-11-24 14:08:47

{'stat': 'Not_Ok', 'Emsg': 'No Data'} 2022-11-24 14:08:47

Please help on priority

Regards
Bhavesh Varshney

**Comment by bhvarshn** [comment]
team please respond. its urgent
