### ISSUE TITLE
How to generate API key programmatically

### ISSUE THREAD

**Issue by yogesh249** [jerokpradeep/pya3#68]
I have to refresh the api key every few days. Can it be done programmatically?

Kindly share some sample code to do that ?

**Comment by srinidhihebbar260297** [comment]
Set up TOTP using external authentication and use selenium to automate the process, working on the code for personal use, will send it once it is done

**Comment by overdoseod** [comment]
> Set up TOTP using external authentication and use selenium to automate the process, working on the code for personal use, will send it once it is done

any update?

**Comment by srinidhihebbar260297** [comment]
I am not using ALICE API anymore or thier brokerage for that matter until https://github.com/jerokpradeep/pya3/issues/70#issue-1517108429 is resolved, it's okay to pay a fixed amount to zerodha as I am answerable to clients, will get back once I get an update on this , as of now I have automated login flow in zerodha
