### ISSUE TITLE
Place Order: Session Expired Error

### ISSUE THREAD

**Issue by vinitshetty** [jerokpradeep/pya3#7]
[{'stat': 'Not_Ok', 'Emsg': 'Session Expired'}]

Other APIs works fine but place_order fails

<img width="725" alt="image" src="https://user-images.githubusercontent.com/30681948/179492215-057b106f-5f1d-4f22-8dd6-d43187f81d23.png">

**Comment by Vignesh-Devoloper** [comment]
Before place order give session request like following
`session_id=alice.get_session_id()`
After this try to place the order.
