### ISSUE TITLE
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'

### ISSUE THREAD

**Issue by hemanth72k** [jerokpradeep/pya3#77]
### im getting a error while im trying to fetch the data
```
**`from datetime import datetime

alice = Aliceblue(user_id = ' secret ',api_key = " secret ")

instrument = alice.get_instrument_by_symbol("NFO", "RELIANCE")
from_datetime = datetime.now() - datetime.timedelta(days=7)     # From last & days
to_datetime = datetime.now()                                    # To now
interval = "1"       # ["1", "D"]
indices = False      # For Getting index data
print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))`**
```

### and this is the output

**AttributeError                            Traceback (most recent call last)
[<ipython-input-22-8aa911090bd6>](https://localhost:8080/#) in <module>
      4 
      5 instrument = alice.get_instrument_by_symbol("NFO", "RELIANCE")
----> 6 from_datetime = datetime.now() - datetime.timedelta(days=7)     # From last & days
      7 to_datetime = datetime.now()                                    # To now
      8 interval = "1"       # ["1", "D"]

AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'**

**Comment by Vignesh-Devoloper** [comment]
Hi @hemanth72k you have to add in your library like below:
from datetime import datetime,timedelta
