### ISSUE TITLE
Major: Session Expires when user logout from UI https://a3.aliceblueonline.com/

### ISSUE THREAD

**Issue by vinitshetty** [jerokpradeep/pya3#8]
API session becomes invalid when user session ends in Web UI.

**Comment by Vignesh-Devoloper** [comment]
The session id work when the user is logged in to the respected trading account at least once a day either web or mobile. This rule is followed by SEBI regulation. If the user is logout the session will be expired and a new session will be generated after the login.

**Comment by vinitshetty** [comment]
to use APIs - user has to be logged in in web or app whole day?

**Comment by Vignesh-Devoloper** [comment]
Yes. Also, the user shouldn't log in to either the older version of the web or mobile application the session will not be valid.
