### ISSUE TITLE
Order History Metadata Format

### ISSUE THREAD

**Issue by vinitshetty** [jerokpradeep/pya3#9]
Could you please map columns as per old format. 

New Format:

[{'Prc': '126.90', 'Action': 'B', 'productcode': 'NRML', 'reporttype': 'exch cancel', 'triggerprice': '120.9', 'filledShares': 0, 'disclosedqty': '0', 'exchangetimestamp': '18-Jul-2022 12:25:01', 'symbolname': 'NIFTY', 'ExchTimeStamp': '18/07/2022 15:33:30', 'nestordernumber': '220718000094808', 'duration': 'DAY', 'OrderUserMessage': '', 'averageprice': '0.0', 'Qty': 100, 'ordergenerationtype': '--', 'modifiedBy': '--', 'filldateandtime': '-- --', 'Status': 'cancelled', 'rejectionreason': '--', 'stat': 'Ok', 'PriceDenomenator': '1', 'exchangeorderid': '1100000032867596', 'PriceNumerator': '1', 'legorderindicator': '', 'customerfirm': 'C', 'ordersource': 'NEST_REST_WEB', 'GeneralDenomenator': '1', 'nestreqid': '1', 'Ordtype': 'SL', 'unfilledSize': 0, 'scripname': '', 'exchange': 'NFO', 'GeneralNumerator': '1', 'bqty': 50, 'Trsym': 'NIFTY2272116200PE'}, {'Prc': '126.90', 'Action': 'B', 'productcode': 'NRML', 'reporttype': 'status', 'triggerprice': '120.9', 'filledShares': 0, 'disclosedqty': '0', 'exchangetimestamp': '18-Jul-2022 12:25:01', 'symbolname': 'NIFTY', 'ExchTimeStamp': '18/07/2022 15:33:30', 'nestordernumber': '220718000094808', 'duration': 'DAY', 'OrderUserMessage': '', 'averageprice': '0.0', 'Qty': 100, 'ordergenerationtype': '--', 'modifiedBy': '--', 'filldateandtime': '-- --', 'Status': 'open', 'rejectionreason': '--', 'stat': 'Ok', 'PriceDenomenator': '1', 'exchangeorderid': '1100000032867596', 'PriceNumerator': '1', 'legorderindicator': '', 'customerfirm': 'C', 'ordersource': 'NEST_REST_WEB', 'GeneralDenomenator': '1', 'nestreqid': '1', 'Ordtype': 'SL', 'unfilledSize': 100, 'scripname': '', 'exchange': 'NFO', 'GeneralNumerator': '1', 'bqty': 50, 'Trsym': 'NIFTY2272116200PE'}, {'Prc': '126.90', 'Action': 'B', 'productcode': 'NRML', 'reporttype': 'sl status', 'triggerprice': '120.9', 'filledShares': 0, 'disclosedqty': '0', 'exchangetimestamp': '18-Jul-2022 12:25:01', 'symbolname': 'NIFTY', 'ExchTimeStamp': '18/07/2022 12:25:01', 'nestordernumber': '220718000094808', 'duration': 'DAY', 'OrderUserMessage': '', 'averageprice': '0.0', 'Qty': 100, 'ordergenerationtype': '--', 'modifiedBy': '--', 'filldateandtime': '-- --', 'Status': 'trigger pending', 'rejectionreason': '--', 'stat': 'Ok', 'PriceDenomenator': '1', 'exchangeorderid': '1100000032867596', 'PriceNumerator': '1', 'legorderindicator': '', 'customerfirm': 'C', 'ordersource': 'NEST_REST_WEB', 'GeneralDenomenator': '1', 'nestreqid': '1', 'Ordtype': 'SL', 'unfilledSize': 100, 'scripname': '', 'exchange': 'NFO', 'GeneralNumerator': '1', 'bqty': 50, 'Trsym': 'NIFTY2272116200PE'}, {'Prc': '126.90', 'Action': 'B', 'productcode': 'NRML', 'reporttype': 'open pending', 'triggerprice': '120.9', 'filledShares': 0, 'disclosedqty': '0', 'exchangetimestamp': '--', 'symbolname': 'NIFTY', 'ExchTimeStamp': '18/07/2022 12:25:01', 'nestordernumber': '220718000094808', 'duration': 'DAY', 'OrderUserMessage': '', 'averageprice': '0.0', 'Qty': 100, 'ordergenerationtype': '--', 'modifiedBy': '--', 'filldateandtime': '-- --', 'Status': 'open pending', 'rejectionreason': '--', 'stat': 'Ok', 'PriceDenomenator': '1', 'exchangeorderid': None, 'PriceNumerator': '1', 'legorderindicator': '', 'customerfirm': 'C', 'ordersource': 'NEST_REST_WEB', 'GeneralDenomenator': '1', 'nestreqid': '1', 'Ordtype': 'SL', 'unfilledSize': 100, 'scripname': '', 'exchange': 'NFO', 'GeneralNumerator': '1', 'bqty': 50, 'Trsym': 'NIFTY2272116200PE'}, {'Prc': '126.90', 'Action': 'B', 'productcode': 'NRML', 'reporttype': 'validation pending', 'triggerprice': '120.9', 'filledShares': 0, 'disclosedqty': '0', 'exchangetimestamp': '--', 'symbolname': 'NIFTY', 'ExchTimeStamp': '18/07/2022 12:25:01', 'nestordernumber': '220718000094808', 'duration': 'DAY', 'OrderUserMessage': '', 'averageprice': '0.0', 'Qty': 100, 'ordergenerationtype': '--', 'modifiedBy': '--', 'filldateandtime': '-- --', 'Status': 'validation pending', 'rejectionreason': '--', 'stat': 'Ok', 'PriceDenomenator': '1', 'exchangeorderid': None, 'PriceNumerator': '1', 'legorderindicator': '', 'customerfirm': 'C', 'ordersource': 'NEST_REST_WEB', 'GeneralDenomenator': '1', 'nestreqid': '1', 'Ordtype': 'SL', 'unfilledSize': 100, 'scripname': '', 'exchange': 'NFO', 'GeneralNumerator': '1', 'bqty': 50, 'Trsym': 'NIFTY2272116200PE'}, {'Prc': '126.90', 'Action': 'B', 'productcode': 'NRML', 'reporttype': 'NA', 'triggerprice': '120.9', 'filledShares': 0, 'disclosedqty': '0', 'exchangetimestamp': '--', 'symbolname': 'NIFTY', 'ExchTimeStamp': '18/07/2022 12:25:01', 'nestordernumber': '220718000094808', 'duration': 'DAY', 'OrderUserMessage': '', 'averageprice': '0.0', 'Qty': 100, 'ordergenerationtype': '--', 'modifiedBy': '--', 'filldateandtime': '-- --', 'Status': 'put order req received', 'rejectionreason': '--', 'stat': 'Ok', 'PriceDenomenator': '1', 'exchangeorderid': None, 'PriceNumerator': '1', 'legorderindicator': '', 'customerfirm': 'C', 'ordersource': 'NEST_REST_WEB', 'GeneralDenomenator': '1', 'nestreqid': '1', 'Ordtype': 'SL', 'unfilledSize': 100, 'scripname': '', 'exchange': 'NFO', 'GeneralNumerator': '1', 'bqty': 50, 'Trsym': 'NIFTY2272116200PE'}]

Old Format: 

{'status': 'success',
 'message': '',
 'data': [{'validity': None,
   'trigger_price': 120.9,
   'transaction_type': 'B',
   'trading_symbol': 'NIFTY2272116200PE',
   'rejection_reason': '--',
   'quantity': 100,
   'product': 'NRML',
   'price_to_fill': 126.9,
   'order_status': 'cancelled',
   'oms_order_id': '220718000094808',
   'nest_request_id': None,
   'filled_quantity': 0,
   'exchange_time': '18-Jul-2022 12:25:01',
   'exchange_order_id': '1100000032867596',
   'exchange': 'NFO',
   'disclosed_quantity': '0',
   'client_id': '411450',
   'average_price': 0.0},
  {'validity': None,
   'trigger_price': 120.9,
   'transaction_type': 'B',
   'trading_symbol': 'NIFTY2272116200PE',
   'rejection_reason': '--',
   'quantity': 100,
   'product': 'NRML',
   'price_to_fill': 126.9,
   'order_status': 'open',
   'oms_order_id': '220718000094808',
   'nest_request_id': None,
   'filled_quantity': 0,
   'exchange_time': '18-Jul-2022 12:25:01',
   'exchange_order_id': '1100000032867596',
   'exchange': 'NFO',
   'disclosed_quantity': '0',
   'client_id': '411450',
   'average_price': 0.0},
  {'validity': None,
   'trigger_price': 120.9,
   'transaction_type': 'B',
   'trading_symbol': 'NIFTY2272116200PE',
   'rejection_reason': '--',
   'quantity': 100,
   'product': 'NRML',
   'price_to_fill': 126.9,
   'order_status': 'trigger pending',
   'oms_order_id': '220718000094808',
   'nest_request_id': None,
   'filled_quantity': 0,
   'exchange_time': '18-Jul-2022 12:25:01',
   'exchange_order_id': '1100000032867596',
   'exchange': 'NFO',
   'disclosed_quantity': '0',
   'client_id': '411450',
   'average_price': 0.0},
  {'validity': None,
   'trigger_price': 120.9,
   'transaction_type': 'B',
   'trading_symbol': 'NIFTY2272116200PE',
   'rejection_reason': '--',
   'quantity': 100,
   'product': 'NRML',
   'price_to_fill': 126.9,
   'order_status': 'open pending',
   'oms_order_id': '220718000094808',
   'nest_request_id': None,
   'filled_quantity': 0,
   'exchange_time': '--',
   'exchange_order_id': None,
   'exchange': 'NFO',
   'disclosed_quantity': '0',
   'client_id': '411450',
   'average_price': 0.0},
  {'validity': None,
   'trigger_price': 120.9,
   'transaction_type': 'B',
   'trading_symbol': 'NIFTY2272116200PE',
   'rejection_reason': '--',
   'quantity': 100,
   'product': 'NRML',
   'price_to_fill': 126.9,
   'order_status': 'validation pending',
   'oms_order_id': '220718000094808',
   'nest_request_id': None,
   'filled_quantity': 0,
   'exchange_time': '--',
   'exchange_order_id': None,
   'exchange': 'NFO',
   'disclosed_quantity': '0',
   'client_id': '411450',
   'average_price': 0.0},
  {'validity': None,
   'trigger_price': 120.9,
   'transaction_type': 'B',
   'trading_symbol': 'NIFTY2272116200PE',
   'rejection_reason': '--',
   'quantity': 100,
   'product': 'NRML',
   'price_to_fill': 126.9,
   'order_status': 'put order req received',
   'oms_order_id': '220718000094808',
   'nest_request_id': None,
   'filled_quantity': 0,
   'exchange_time': '--',
   'exchange_order_id': None,
   'exchange': 'NFO',
   'disclosed_quantity': '0',
   'client_id': '411450',
   'average_price': 0.0}]}

**Comment by Vignesh-Devoloper** [comment]
Hi Vinut, we added the order history wrapper in pya3 version 1.0.16 which helps to covert the current API response to the old API response. Please update and check once
