### ISSUE TITLE
alice.get_scrip_info() function is not working

### ISSUE THREAD

**Issue by Fazle-hasan** [jerokpradeep/pya3#90]
I change my password of alice blue account after that alice.get_scrip_info() is not working. 

Example

input: banknifty = alice.get_instrument_by_symbol('INDICES','NIFTY BANK')

print(alice.get_scrip_info(banknifty))

Output: {'emsg': None, 'stat': 'Not_Ok'}

**Comment by vikram3294** [comment]
Facing the same error since last week. Some accounts are facing this issue. Some aren't. Need some clarity if there is an endpoint change.
